<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">  
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <title>MiniCRM</title>

        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="css/common.css" rel="stylesheet">
    <body>
        <main role="main" class="flex-shrink-0">
            <div class="container">
                <div id="bl">
                </div>
                <div class="row">
                    <h1 class="mt-5">MiniCRM - Companies</h1>
                </div>
                <div class="row">
                    <div class="col-lg">
                        <table class="table table-striped">
                            <thead>
                                <td>#</td>
                                <td>Company</td>
                                <td>Type</td>
                                <td><button id="add" class="btn btn-sm btn-success">Add</button></td>
                            </thead>
                            <tbody>
                                <?php
                                foreach($companies as $company){
                                ?>
                                    <tr>
                                        <td><?php echo $company->id; ?></td>
                                        <td><?php echo $company->get_header(); ?></td>
                                        <td><?php echo $company->type; ?></td>
                                        <td>
                                            <button class="btn btn-sm btn-primary modify" data-id="<?php echo $company->id; ?>">Edit</button>
                                            <button class="btn btn-sm btn-danger delete" data-id="<?php echo $company->id; ?>">Delete</button>
                                        </td>
                                    </tr>
                                <?php
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-lg">
                        <hr>
                    </div>
                </div>

                <div class="row companydetails">
                    
                </div>
            </div>

            <div class="modal" style="display: none" tabindex="-1" role="dialog">
            </div>
        </main>

        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="js/index.js"></script>
    </body>
</html>
