<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Update Contact</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="container-fluid">
                <div class="row">
                    <label for="name">Name</label><input id="name" type="text" class="form-control" value="<?php echo $contact_details->name; ?>">
                    <label for="phone">Phone</label><input id="phone" type="text" class="form-control" value="<?php echo $contact_details->phone; ?>">
                </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="update_contact">Save</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Discard</button>
        </div>
    </div>
</div>
